### PR TITLE
Fix builds with linux kernel 6.9

### PR DESCRIPTION
**Pull request by hellcwang**
Using similar method in [github:rtl88x2bu - fix build for Linux 6.9](https://github.com/cilynx/rtl88x2bu/commit/287e766d19a6bc9c61718d77aebfa8a7a6f92461) fix the API change in kernel 6.9.0

### CODE REVIEW

**Comment by dubhater** [comment]
Do you get a wifi interface with this driver if you fix the compilation errors?

**Comment by hellcwang** [comment]
@dubhater I have a tp-link archer TX20U Plus with me which using RTL8188GU. The usb id is 0bda:1a2b.
After fixing the compilation error, the driver works well on `6.9.9-arch1-1`

**Comment by dubhater** [comment]
0bda:1a2b is the CDROM mode ID used by many different devices with Realtek chips, not just RTL8188GU. If you eject it, you will get the true USB ID. You can install usb_modeswitch to automate the switching.

TX20U is a wifi 6 device. The driver in this repository is only for one specific wifi 4 chip.

**Comment by hellcwang** [comment]
The true USB ID is 2357:013f. 

>TX20U is a wifi 6 device. The driver in this repository is only for one specific wifi 4 chip.

~~I think that is the reason why I cannot get the full speed with this device, thanks.~~
The working driver for the TX20U is [rtl8852au](https://github.com/lwfinger/rtl8852au). Sorry I messed it up.

**Comment by predefine** [comment]
this pull request will not pushed, larry is passed away :(

**Comment by hellcwang** [comment]
I am so sorry to hear that. 
I will close this PR.
