### ISSUE TITLE
Not buildable with kernel 5.10

### ISSUE THREAD

**Issue by mikhailnov** [lwfinger/rtl8188gu#11]
This code is not buildable with kernel 5.10. Builds ok with kernel 5.15.
I actually do not need it for 5.10, just reporting this issue to make you know this))

```
$ LC_ALL=C make CC='LC_ALL=C gcc' KVER=5.10.147-generic-2rosa2021.1-x86_64
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.10.147-generic-2rosa2021.1-x86_64/build M=/tmp/rtl8188gu  modules
make[1]: Entering directory '/usr/src/linux-5.10.147-generic-2rosa2021.1-x86_64'
  CC [M]  /tmp/rtl8188gu/core/rtw_cmd.o
In file included from /tmp/rtl8188gu/include/drv_types.h:78,
                 from /tmp/rtl8188gu/core/rtw_cmd.c:17:
/tmp/rtl8188gu/include/rtw_security.h:253:8: error: redefinition of 'struct sha256_state'
  253 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:24,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:87,
                 from ./include/net/addrconf.h:52,
                 from /tmp/rtl8188gu/include/osdep_service_linux.h:48,
                 from /tmp/rtl8188gu/include/osdep_service.h:47,
                 from /tmp/rtl8188gu/include/drv_types.h:27,
                 from /tmp/rtl8188gu/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:286: /tmp/rtl8188gu/core/rtw_cmd.o] Ошибка 1
make[1]: *** [Makefile:1820: /tmp/rtl8188gu] Error 2
make[1]: Leaving directory '/usr/src/linux-5.10.147-generic-2rosa2021.1-x86_64'
make: *** [Makefile:1522: modules] Error 2
```
